export const variables = [
  {
    full_name: '269,1,ZN_1_FLR_1_SEC_1,Zone Mean Air Temperature [C] !Hourly',
    id: 1,
    is_meter: 0,
    name: 'ZN_1_FLR_1_SEC_1,Zone Mean Air Temperature',
    simulation_id: 9,
    type: 'hourly',
    units: 'C',
  },
  {
    full_name: '270,1,ZN_1_FLR_1_SEC_2,Zone Mean Air Temperature [C] !Hourly',
    id: 2,
    is_meter: 0,
    name: 'ZN_1_FLR_1_SEC_2,Zone Mean Air Temperature',
    simulation_id: 9,
    type: 'hourly',
    units: 'C',
  },
  {
    full_name: '271,1,ZN_1_FLR_1_SEC_3,Zone Mean Air Temperature [C] !Hourly',
    id: 3,
    is_meter: 0,
    name: 'ZN_1_FLR_1_SEC_3,Zone Mean Air Temperature',
    simulation_id: 9,
    type: 'hourly',
    units: 'C',
  },
  {
    full_name: '272,1,ZN_1_FLR_1_SEC_4,Zone Mean Air Temperature [C] !Hourly',
    id: 4,
    is_meter: 0,
    name: 'ZN_1_FLR_1_SEC_4,Zone Mean Air Temperature',
    simulation_id: 9,
    type: 'hourly',
    units: 'C',
  },
  {
    full_name: '273,1,ZN_1_FLR_1_SEC_5,Zone Mean Air Temperature [C] !Hourly',
    id: 5,
    is_meter: 0,
    name: 'ZN_1_FLR_1_SEC_5,Zone Mean Air Temperature',
    simulation_id: 9,
    type: 'hourly',
    units: 'C',
  },
  {
    full_name: '683,1,ZN_1_FLR_1_SEC_1,Zone Heating Setpoint Not Met Time [hr] !Hourly',
    id: 6,
    is_meter: 0,
    name: 'ZN_1_FLR_1_SEC_1,Zone Heating Setpoint Not Met Time',
    simulation_id: 9,
    type: 'hourly',
    units: 'hr',
  },
  {
    full_name: '684,1,ZN_1_FLR_1_SEC_1,Zone Heating Setpoint Not Met While Occupied Time [hr] !Hourly',
    id: 7,
    is_meter: 0,
    name: 'ZN_1_FLR_1_SEC_1,Zone Heating Setpoint Not Met While Occupied Time',
    simulation_id: 9,
    type: 'hourly',
    units: 'hr',
  },
  {
    full_name: '685,1,ZN_1_FLR_1_SEC_2,Zone Heating Setpoint Not Met Time [hr] !Hourly',
    id: 8,
    is_meter: 0,
    name: 'ZN_1_FLR_1_SEC_2,Zone Heating Setpoint Not Met Time',
    simulation_id: 9,
    type: 'hourly',
    units: 'hr',
  },
  {
    full_name: '686,1,ZN_1_FLR_1_SEC_2,Zone Heating Setpoint Not Met While Occupied Time [hr] !Hourly',
    id: 9,
    is_meter: 0,
    name: 'ZN_1_FLR_1_SEC_2,Zone Heating Setpoint Not Met While Occupied Time',
    simulation_id: 9,
    type: 'hourly',
    units: 'hr',
  },
  {
    full_name: '687,1,ZN_1_FLR_1_SEC_3,Zone Heating Setpoint Not Met Time [hr] !Hourly',
    id: 10,
    is_meter: 0,
    name: 'ZN_1_FLR_1_SEC_3,Zone Heating Setpoint Not Met Time',
    simulation_id: 9,
    type: 'hourly',
    units: 'hr',
  },
  {
    full_name: '688,1,ZN_1_FLR_1_SEC_3,Zone Heating Setpoint Not Met While Occupied Time [hr] !Hourly',
    id: 11,
    is_meter: 0,
    name: 'ZN_1_FLR_1_SEC_3,Zone Heating Setpoint Not Met While Occupied Time',
    simulation_id: 9,
    type: 'hourly',
    units: 'hr',
  },
];

export const chartPie = {
  chart_data: '',
  chart_name: 'tony-pie-variables',
  created_at: '2020-09-18T15:27:19.000000Z',
  id: 9,
  options: { variables: [] },
  variables: [],
  parent_simulation_id: 9,
  type: 'pie',
  updated_at: '2020-09-18T15:27:19.000000Z',
};

export const chartData = [
  {
    group: '272,1,ZN_1_FLR_1_SEC_4,Zone Mean Air Temperature [C] !Hourly',
    value: 12.730884941006776,
  },
  {
    group: '270,1,ZN_1_FLR_1_SEC_2,Zone Mean Air Temperature [C] !Hourly',
    value: 12.729213885179492,
  },
  {
    group: '271,1,ZN_1_FLR_1_SEC_3,Zone Mean Air Temperature [C] !Hourly',
    value: 12.722719046658694,
  },
];

export const labels = {
  '269,1,ZN_1_FLR_1_SEC_1,Zone Mean Air Temperature [C] !Hourly': '#1b5589',
  '270,1,ZN_1_FLR_1_SEC_2,Zone Mean Air Temperature [C] !Hourly:': '#0d912c',
  '271,1,ZN_1_FLR_1_SEC_3,Zone Mean Air Temperature [C] !Hourly:': '#6f6a6d',
};

export const variableValues = [
  {
    datetime: '2001-01-21 00:00:00',
    max_datetime: null,
    max_value: null,
    min_datetime: null,
    min_value: null,
    output_variable_id: 1,
    value: '12.722719046658695',
  },
  {
    datetime: '2001-01-21 00:00:00',
    max_datetime: null,
    max_value: null,
    min_datetime: null,
    min_value: null,
    output_variable_id: 1,
    value: '12.438386882967225',
  },
  {
    datetime: '2001-07-21 07:00:00',
    max_datetime: null,
    max_value: null,
    min_datetime: null,
    min_value: null,
    output_variable_id: 1,
    value: '21.00050013819113',
  },
  {
    datetime: '2001-08-21 11:00:00',
    max_datetime: null,
    max_value: null,
    min_datetime: null,
    min_value: null,
    output_variable_id: 1,
    value: '32.239954585543959',
  },
  {
    datetime: '2001-09-21 23:00:00',
    max_datetime: null,
    max_value: null,
    min_datetime: null,
    min_value: null,
    output_variable_id: 1,
    value: '29.56697788614609',
  },
];
